# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
            AppBundle\Entity\User: { algorithm: sha512 }

    providers:
            users:
                entity: { class: AppBundle\Entity\User, property: username }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/api/v1/login
            stateless: true
            anonymous: true
            provider: users
            form_login:
                check_path:               /api/v1/login_check
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false

        api:
            anonymous: ~
            pattern:   ^/api/v1
            stateless: true
            provider: users
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

    access_control:
        - { path: ^/api/v1/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/v1/users, roles: IS_AUTHENTICATED_ANONYMOUSLY, methods: [POST]  }
        - { path: ^/api/v1,       roles: IS_AUTHENTICATED_FULLY }